const D=window.CODEVA_DATA;let progress=JSON.parse(localStorage.getItem("codeva_progress")||"{}");let currentCourse=null,currentLesson=0;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem("codeva_progress",JSON.stringify(progress))}
function goHome(){renderHome();scrollTo(0,0)}
function renderHome(){
document.body.innerHTML=`<nav class="nav"><div class="brand">Code<span>va</span>.</div><div class="navlinks"><button onclick="goHome()">الرئيسية</button><button onclick="scrollToId('courses')">الكورسات</button><button onclick="scrollToId('videos')">فيديوهات عربية</button></div><button class="btn primary" onclick="scrollToId('courses')">ابدأ التعلم</button></nav><main class="container"><section class="hero"><span class="badge">منصة تعليم برمجة عربية</span><h1>اتعلم البرمجة<br><span>بالفهم والتطبيق.</span></h1><p>كورسات مكتوبة بالكامل، تمارين ومشاريع، ومع كل مسار مصادر فيديو عربية مختارة. تقدمك محفوظ على جهازك بدون حساب.</p><div class="toolbar"><input class="input" id="search" placeholder="🔎 ابحث عن كورس أو مهارة..." oninput="filter()"></div></section><section id="courses"><div class="grid">${D.courses.map(courseCard).join("")}</div></section><section class="videos" id="videos"><h2>فيديوهات عربية مساعدة 🎬</h2><p style="color:var(--muted)">الفيديوهات من YouTube ومضمنة داخل المنصة؛ المحتوى المكتوب مستقل عنها.</p><div class="grid">${D.videos.map(v=>`<article class="videoCard"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}" title="${v.title}" loading="lazy" allowfullscreen></iframe><div><b>${v.title}</b><p>${v.author} — ${v.desc}</p></div></article>`).join("")}</div></section></main><footer>Codeva © 2026 — تعلم، طبّق، وابنِ.</footer>`;
}
function courseCard(c){let done=c.lessons.filter(x=>progress[x.id]).length,p=Math.round(done/c.lessons.length*100);return `<article class="card" data-search="${(c.title+c.desc+c.level).toLowerCase()}" onclick="openCourse('${c.id}')"><div class="icon">${c.icon}</div><span class="tag">${c.level}</span><h3>${c.title}</h3><p>${c.desc}</p><div class="progress"><i style="width:${p}%"></i></div><div class="meta"><span>${c.lessons.length} دروس</span><span>${p}% مكتمل</span></div></article>`}
function filter(){let q=$("#search").value.toLowerCase();document.querySelectorAll(".card").forEach(c=>c.style.display=c.dataset.search.includes(q)?"block":"none")}
function openCourse(id){currentCourse=D.courses.find(c=>c.id===id);currentLesson=0;renderCourse()}
function renderCourse(){let c=currentCourse;document.body.innerHTML=`<nav class="nav"><div class="brand">Code<span>va</span>.</div><div class="navlinks"><button onclick="goHome()">الرئيسية</button><button onclick="openCourse('${c.id}')">الكورس</button></div><button class="btn ghost" onclick="goHome()">← رجوع</button></nav><main class="container"><div class="coursehead"><div class="icon">${c.icon}</div><div><span class="badge">${c.level}</span><h1>${c.title}</h1><p style="color:var(--muted)">${c.desc}</p></div></div><div class="lessons"><aside class="sidebar">${c.lessons.map((l,i)=>`<button class="lessonbtn ${i===currentLesson?"active":""}" onclick="showLesson(${i})">${progress[l.id]?"✓ ":""}${i+1}. ${l.title}<small>${l.mins} دقيقة</small></button>`).join("")}</aside><article class="lesson" id="lesson"></article></div></main><footer>Codeva © 2026</footer>`;showLesson(currentLesson)}
function showLesson(i){currentLesson=i;let l=currentCourse.lessons[i];$("#lesson").innerHTML=`<span class="badge">الدرس ${i+1} من ${currentCourse.lessons.length}</span><h2>${l.title}</h2>${l.body.split("\\n").map(x=>`<p>${x}</p>`).join("")}<h3>أهم النقاط</h3><ul class="points">${l.points.map(x=>`<li>${x}</li>`).join("")}</ul><h3>مثال عملي</h3><pre class="code">${esc(l.code)}</pre>${l.video?`<div class="video"><h3>فيديو عربي اختياري 🎬</h3><iframe src="https://www.youtube-nocookie.com/embed/${l.video}" title="فيديو الدرس" loading="lazy" allowfullscreen></iframe><p style="color:var(--muted)">الفيديو مصدر خارجي من YouTube؛ يمكنك إكمال المنهج من الشرح المكتوب فقط.</p></div>`:""}<div class="check"><button class="btn ${progress[l.id]?"ghost":"primary"}" onclick="toggleDone('${l.id}')">${progress[l.id]?"✓ تم إكمال الدرس":"تحديد الدرس كمكتمل"}</button> <button class="btn ghost" onclick="nextLesson()">${i===currentCourse.lessons.length-1?"إنهاء الكورس":"الدرس التالي →"}</button></div>`;document.querySelectorAll(".lessonbtn").forEach((b,j)=>b.classList.toggle("active",j===i))}
function toggleDone(id){progress[id]=!progress[id];save();renderCourse()}
function nextLesson(){if(currentLesson<currentCourse.lessons.length-1){currentLesson++;renderCourse()}else goHome()}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
renderHome();